account/urls.py
# -*- coding: utf-8 -*-

from flask import Blueprint

import views

accounts = Blueprint("accounts", __name__)

accounts.add_url_rule("/login/", "login", views.login, methods=["GET", "POST"])
accounts.add_url_rule("/logout/", "logout", views.logout)
accounts.add_url_rule("/registration/", "register", views.register, methods=["GET", "POST"])
accounts.add_url_rule("/registration/su", "register_su", views.register, defaults={"create_su":True}, methods=["GET", "POST"])
accounts.add_url_rule("/add-user/", "add_user", views.add_user, methods=["GET", "POST"])
accounts.add_url_rule('/users/', view_func=views.Users.as_view('users'))
accounts.add_url_rule('/users/edit/<username>', view_func=views.User.as_view("edit_user"))
accounts.add_url_rule('/user/settings/', view_func=views.Profile.as_view('settings'))
accounts.add_url_rule('/user/password/', view_func=views.Password.as_view('password'))
accounts.add_url_rule('/su-users/', view_func=views.SuUsers.as_view('su_users'))
accounts.add_url_rule('su-users/edit/<username>', view_func=views.SuUser.as_view("su_edit_user"))

main/urls.py
# -*- coding: utf-8 -*-

from flask import Blueprint

import views
import admin_views
import errors

main = Blueprint("main", __name__)
# __name__ : main.urls


main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail)
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={"fix": True})
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type': "page"})
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)
main.errorhandler(404)(errors.page_not_found)



blog_admin = Blueprint("blog_admin", __name__)

blog_admin.add_url_rule("/", view_func=admin_views.AdminIndex.as_view("index"))
blog_admin.add_url_rule("/posts/", view_func=admin_views.PostsList.as_view("posts"))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('posts/<slug>', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view("su_posts"))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

account/models.py
# -*- coding: utf-8 -*-

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from VchanBlog import db
from VchanBlog import login_manager
from VchanBlog.defines import *

import datetime


class CUser(UserMixin, db.Document):
    username = db.StringField(max_length=255, required=True)
    email = db.EmailField(max_length=255)
    password_hash = db.StringField(required=True)
    create_time = db.DateTimeField(default=datetime.datetime.now, required=True)
    last_login = db.DateTimeField(default=datetime.datetime.now, required=True)
    is_email_confirmed = db.BooleanField(default=False)
    # is_active = db.BooleanField(default=True)
    is_superuser = db.BooleanField(default=False)
    role = db.StringField(max_length=32, default='reader', choices=ROLES)
    display_name = db.StringField(max_length=255, default='Anonymous')
    biography = db.StringField()
    social_networks = db.DictField(default=SOCIAL_NETWORKS)
    homepage_url = db.URLField()

    @property
    def password(self):
        raise AttributeError('password is not a readle attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_id(self):
        try:
            return unicode(self.username)
        except AttributeError:
            raise NotImplementedError('No `username` attribute - override `get_id`')

    def __unicode__(self):
        return self.username

@login_manager.user_loader
def load_user(username):
    try:
        user = CUser.objects.get(username=username)
    except CUser.DoesNotExist:
        user = None
    return user

account/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SelectField, ValidationError
from wtforms.validators import Required, Length, Email, Regexp, EqualTo, URL, Optional
from flask .ext.login import current_user

import models


class LoginForm(Form):
    username = StringField()
    password = PasswordField()
    remember_me = BooleanField("Keep me logged in")

class RegistrationForm(Form):
    username = StringField("Username", validators=[Required(), Length(1, 64),
                           Regexp("^[A-Za-z0-9_.]*$",0, "Usernames must have only letters, numbers dots or underscores")])
    email = StringField("Email", validators=[Required(), Length(1, 128), Email()])
    password = PasswordField("Password", validators=[Required(), Length(1, 128), EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField("Comfirm password", validators=[Required()])

    def validate_username(self, field):
        if models.CUser.objects.filter(username=field.data).count() > 0:
            raise ValidationError("Username already in use")

    def validate_email(self, field):
        if models.CUser.objects.filter(email=field.data).count() > 0:
            raise ValidationError("Email already in registered")

class ProfileForm(Form):
    email = StringField("Email", validators=[Required(), Length(1, 128), Email()])
    display_name = StringField("Display Name", validators=[Length(1, 128)])
    biography = StringField("Biography")
    homepage_url = StringField("Homepage", validators=[URL(), Optional()])
    weibo = StringField("Weibo", validators=[URL(), Optional()])
    weixin = StringField("Weixin", validators=[Optional(), URL()])
    twitter = StringField("Twitter", validators=[URL(), Optional()])
    github = StringField("github", validators=[URL(), Optional()])
    facebook = StringField("Facebook", validators=[URL(), Optional()])
    linkedin = StringField("Linkedin", validators=[URL(), Optional()])


class PasswordForm(Form):
    current_password = PasswordField("Current Password", validators=[Required()])
    new_password = PasswordField("New Password", validators=[Required(), EqualTo("password2", message="Password must match")])
    password2 = PasswordField("Confirm password", validators=[Required()])

    def validate_current_password(self, field):
        if not current_user.verify_password(field.data):
            raise ValidationError("Current password is wrong")


class UserForm(Form):
    email = StringField("Email", validators=[Required(), Length(1,128), Email()])
    role = SelectField("Role", choices=models.ROLES)

class SuUserForm(Form):
    email = StringField("Email", validators=[Required(), Length(1,128), Email()])
    is_superuser = BooleanField("Is superuser")
    is_email_confirmed = BooleanField("Is Email Confirmed")
    role = SelectField("Role", choices=models.ROLES)
    display_name = StringField("Display Name", validators=[Length(1,128)])
    biography = StringField("Biography")
    homepage_url = SelectField("Homepage", validators=[URL(), Optional()])
    weibo = StringField("Weibo", validators=[URL(), Optional()])
    weixin = StringField("Weixin", validators=[URL(), Optional()])
    twitter = StringField("Twitter", validators=[URL(), Optional()])
    github = StringField("github", validators=[URL(), Optional()])
    facebook = StringField("Facebook", validators=[URL(), Optional()])
    weibo = StringField("Linkedin", validators=[URL(), Optional()])

account/views.py
# -*- coding: utf-8 -*-

from VchanBlog.defines import *
from flask_login import login_user, logout_user, login_required, current_user
from flask_principal import identity_changed, AnonymousIdentity, Identity
from flask import render_template, redirect, request, flash, url_for, current_app, session
from flask.views import MethodView
from permissions import admin_permission, su_permission

import forms
import models
import datetime

def login():
    form = forms.LoginForm()
    if form.validate_on_submit():
        try:
            user = models.CUser.objects.get(username=form.username.data)
        except models.CUser.DoesNotExist:
            user = None

        if user and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            user.last_login = datetime.datetime.now
            user.save()
            identity_changed.send(current_app._get_current_object(), identity=Identity(user.username))
            return redirect(request.args.get("next") or url_for("blog_admin.index"))

        flash("Invalid username or password", "danger")

    return render_template("accounts/login.html", form=form)

@login_required
def logout():
    logout_user()

    for key in ("identity.name", "identity.auth_type"):
        session.pop(key, None)

    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())

    flash("You have been logged out", "success")
    return redirect(url_for("accounts.login"))

def register(create_su=False):
    if not VchanBlogSettings["allow_registration"]:
        msg = "Register is forbidden, please contact administrator"
        return msg
    if create_su and not VchanBlogSettings["allow_su_creation"]:
        msg = "Register superuser is forbidden, please contact administrator"
        return msg

    form = forms.RegistrationForm()
    if form.validate_on_submit():
        user = models.CUser()
        user.username = form.username.data
        user.password = form.password.data
        user.email = form.email.data

        user.display_name = user.username

        if create_su and VchanBlogSettings["allow_su_creation"]:
            user.is_superuser = True

        user.save()

        return redirect(url_for("main.index"))

    return render_template("accounts/registration.html", form=form)

@login_required
def add_user():
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        user = models.CUser()
        user.username = form.username.data
        user.password = form.password.data
        user.email = form.email.data
        user.display_name = user.username
        user.save()
        return redirect(url_for("accounts.users"))
    return render_template("accounts/registration.html")

def get_current_user():
    user = models.CUser.objects.get(username=current_user.username)
    return user


class Profile(MethodView):
    decorators = [login_required]
    template_name = "accounts/settings.html"

    def get(self, form=None):
        if not form:
            user = current_user
            user.weibo = user.social_networks["weibo"].get("url")
            user.weixin = user.social_networks["weixin"].get("url")
            user.twitter = user.social_networks["twitter"].get("url")
            user.github = user.social_networks["github"].get("url")
            user.facebook = user.social_networks["facebook"].get("url")
            user.linkedin = user.social_networks["linkedin"].get("url")
            form = forms.ProfileForm(obj=user)
        data = {"form":form}
        return render_template(self.template_name, **data)

    def post(self):
        form = forms.ProfileForm(obj=request.form)
        if form.validate():
            user = current_user
            if user.email != form.email.data:
                user.email = form.email.data
                user.is_email_comfirmed = False

            user.display_name = form.display_name.data
            user.biography = form.biography.data
            user.homepage_url = form.homepage_url.data
            user.social_networks["weibo"]["url"] = form.weibo.data or None
            user.social_networks["weixin"]["url"] = form.weixin.data or None
            user.social_networks["twitter"]["url"] = form.twitter.data or None
            user.social_networks["github"]["url"] = form.github.data or None
            user.social_networks["facebook"]["url"] = form.facebook.data or None
            user.social_networks["linkedin"]["url"] = form.linkedin.data or None
            user.save()

            msg = "Succeed to update user profile"
            flash(msg, "success")

            return redirect(url_for("blog_admin.index"))

        return self.get(form)


class SuUsers(MethodView):
    decorators = [login_required, su_permission.require(401)]
    template_name = "accounts/su_users.html"
    def get(self):
        users = models.CUser.objects.all()
        return render_template(self.template_name, users=users)

class SuUser(MethodView):
    decorators = [login_required, admin_permission.require(401)]
    template_name = "accounts/user.html"

    def get_context(self, username, form=None):
        if not form:
            user = models.CUser.objects.get_or_404(username=username)
            user.weibo = user.social_networks['weibo'].get("url")
            user.weixin = user.social_networks['weixin'].get("url")
            user.twitter = user.social_networks['twitter'].get('url')
            user.github = user.social_networks['github'].get('url')
            user.facebook = user.social_networks['facebook'].get('url')
            user.linkedin = user.social_networks['linkedin'].get('url')
            form = forms.SuUserForm(obj=user)
        data={'form': form}
        return data

    def get(self, username, form=None):
        data = self.get_context(username, form)
        return render_template(self.template_name, **data)

    def post(self, username):
        form = forms.SuUserForm(obj=request.form)
        if form.validate():
            user = models.CUser.objects.get_or_404(user=username)
            user.email = form.email.data
            user.is_email_comfirmed = form.is_email_comfirmed.data

            user.display_name = form.display_name.data
            user.biography = form.biography.data
            user.homepage_url = form.homepage_url.data or None
            user.social_networks['weibo']['url'] = form.weibo.data or None
            user.social_networks['weixin']['url'] = form.weixin.data or None
            user.social_networks['twitter']['url'] = form.twitter.data or None
            user.social_networks['github']['url'] = form.github.data or None
            user.social_networks['facebook']['url'] = form.facebook.data or None
            user.social_networks['linkedin']['url'] = form.linkedin.data or None
            user.save()

            flash("Succeed to update user profile", 'success')
            return redirect(url_for('accounts.su_edit_user', username=user.username))

        return self.get(form)


class Users(MethodView):
    decorators = [login_required, admin_permission.require(401)]
    template_name = "accounts/users.html"
    def get(self):
        users = models.CUser.objects.all()
        return render_template(self.template_name, users=users)


class User(MethodView):
    decorators = [login_required, admin_permission.require(401)]
    template_name = "accounts/user.html"

    def get_context(self, username, form=None):
        if not form:
            user = models.CUser.objects.get_or_404(username=username)
            form = forms.UserForm(obj=user)
        data = {"form": form}
        return data

    def get(self, username, form=None):
        data = self.get_context(username, form)
        return render_template(self.template_name, **data)

    def post(self, username):
        form = forms.UserForm(obj=request.form)
        if form.validate():
            user = models.CUser.objects.get_or_404(username=username)
            if user.email != form.email.data:
                user.is_email_confirmed = False
            user.email = form.email.data
            user.role = form.role.data
            user.save()
            flash("Succeed to update user details", "success")
            return redirect(url_for("accounts.edit_user", username=username))
        return self.get(username, form)

    def delete(self, username):
        user = models.CUser.objects.get_or_404(username=username)
        user.delete()
        if request.args.get("ajax"):
            return "success"
        flash("Succeed to delete user", "success")
        return redirect(url_for("accounts.users"))

class Password(MethodView):
    decorators = [login_required]
    template_name = "accounts/password.html"

    def get(self, form=None):
        if not form:
            form = forms.PasswordForm()
        data = {"form": form}
        return render_template(self.template_name, **data)

templates/accounts/login.html
{% extends "admin_base.html" %}
{% block title %}Login{% endblock %}
{% block main %}

<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='login'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="login">Login</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>
{% endblock %}

templates/accounts/password.html
{% extends 'admin_base.html' %}
{% block title %} Settings: Change Password {% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <ul class="nav nav-tabs">
          <li role="presentation"><a href="{{ url_for('accounts.settings' )}}">Profile</a></li>
          <li role="presentation" class="active"><a href="#" onclick="return false">Password</a></li>
        </ul>
    </div>
</div>
<br>
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='password'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="update">Update</button>
        </form>
    </div>
    <div 
{% endblock %}

templates/accounts/registration.html
{% extends "admin_base.html" %}
{% block title %}Registration{% endblock %}
{% block main %}

<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='login'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="register">Register</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>
{% endblock %}

templates/accounts/settings.html
{% extends 'admin_base.html' %}
{% block title %} Settings: Update Profile {% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><a href="#" onclick="return false">Profile</a></li>
          <li role="presentation"><a href="{{ url_for('accounts.password') }}">Password</a></li>
        </ul>
    </div>
</div>
<br>
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        {% import "_form.html" as forms %}
        <form method="POST" action="" id='profile'>
        {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="update">Update</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>
{% endblock %}

templates/accounts/su_users.html
{% extends 'admin_base.html' %}

{% block title %}Users{% endblock %}
{% block main %}
<div class="row">
    <div class="col-md-10">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Username</th>
                <th>Email</th>
                <th>Is Active</th>
                <th>Email Confirmed</th>
                <th>Is Superuser</th>
                <th>Actions</th>
            </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr id="user-{{ user.username }}">
            <td>{{ loop.index }}</td>
            <td><a href="{{ url_for('accounts.su_edit_user', username=user.username) }}">{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_active }}</td>
            <td>{{ user.is_email_confirmed }}</td>
            <td>{{ user.is_superuser }}</td>
            <td>
                <a href="{{ url_for('accounts.su_edit_user', username=user.username) }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
            </td>
        </tr>
        {% else %}
        <tr><td colspan="7">No user yet</td></tr>
    {% endfor %}     
    </tbody>
    </table>

    </div>
    <div class="col-md-2">
        <!-- <h4>Filter By Group</h4> -->
        <p><strong>Filter By Role</strong></p>
        <hr>
        <div class="list-group">
          Not yet
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

templates/accounts/user.html
{% extends 'admin_base.html' %}
{% block title %} Edit User {% endblock %}

{% block main %}
<div class="row">
    <div class="col-md-6 col-md-offset-1">
        <h3>User Details</h3>
        <hr>
        {% import "_form.html" as forms %}
        <form method="POST" action="">
            {{ forms.render(form) }}
            <button type="submit" class="btn btn-primary" name="user" value="user">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/users.html
{% extends 'admin_base.html' %}

{% block title %}Users{% endblock %}
{% block main %}
<div class="row">
    <div class="col-md-10">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Username</th>
                <th>Email</th>
                <th>Is Active</th>
                <th>Last Login</th>
                <th>Create Date</th>
                <th>Actions</th>
            </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr id="user-{{ user.username }}">
            <td>{{ loop.counter }}</td>
            <td><a href="{{ url_for('accounts.edit_user', username=user.username) }}">{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_active }}</td>
            <td>{{ user.last_login.strftime('%Y/%m/%d %H:%M:%S') }}</td>
            <td>{{ user.create_time.strftime('%Y/%m/%d') }}</td>
            <td>
                <a href="{{ url_for('accounts.edit_user', username=user.username) }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                &nbsp
                <a href="{{ url_for('accounts.edit_user', username=user.username) }}"  class="del-user"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
            </td>
        </tr>
        {% else %}
        <tr><td colspan="7">No user yet</td></tr>
    {% endfor %}     
    </tbody>
    </table>

    </div>
    <div class="col-md-2">
        <!-- <h4>Filter By Group</h4> -->
        <p><strong>Filter By Role</strong></p>
        <hr>
        <div class="list-group">
          Not yet
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
$('.del-user').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');
    url = url + '?ajax=true';

    bootbox.confirm("Are you sure?", function(result) {
      if(result){
        // $.get(url, function(){
        //     location.reload();
        // });
        $.ajax({
            url: url,
            type: 'DELETE',
            success: function(result){
                location.reload();
            }

        });
        }
    });
    return false;
  });
</script>
{% endblock %}