main/urls.py
# -*- coding: utf-8 -*-

from flask import Blueprint

import views
import admin_views
import errors

main = Blueprint("main", __name__)
# __name__ : main.urls


main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail)
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={"fix": True})
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type': "page"})
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)
main.errorhandler(404)(errors.page_not_found)



blog_admin = Blueprint("blog_admin", __name__)

blog_admin.add_url_rule("/", view_func=admin_views.AdminIndex.as_view("index"))
blog_admin.add_url_rule("/posts/", view_func=admin_views.PostsList.as_view("posts"))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('posts/<slug>', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view("su_posts"))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

main/models.py
# -*- coding: utf-8 -*-

from VchanBlog.defines import *
from flask import url_for
from flask_mongoengine import MongoEngine
from account.models import CUser

import datetime
import markdown2

db = MongoEngine()

class CPost(db.Document):
    title = db.StringField(max_length=255, default='new blog', required=True)
    slug = db.StringField(max_length=255, required=True, unique=True)
    fix_slug = db.StringField(max_length=255, required=False)
    abstract = db.StringField()
    raw = db.StringField(required=True)
    pub_time = db.DateTimeField(required=True)
    update_time = db.DateTimeField(required=True)
    content_html = db.StringField(required=True)
    author = db.ReferenceField(CUser)
    category = db.StringField(max_length=64, default="default")
    tags = db.ListField(db.StringField(max_lenght=30))
    is_draft = db.BooleanField(default=False)
    post_type = db.StringField(max_length=64, default="post")

    def get_absolute_url(self):
        return url_for('main.post_detail', slug=self.slug)

    def save(self, allow_set_time=False, *args, **kwargs):
        if not allow_set_time:
            now = datetime.datetime.now()
            if not self.pub_time:
                self.pub_time = now
            self.update_time = now
        # self.content_html = self.raw
        self.content_html = markdown2.markdown(self.raw, extras=['code-friendly', 'fenced-code-blocks']).encode('utf-8')
        return super(CPost, self).save(*args, **kwargs)

    def set_post_date(self, pub_time, update_time):
        self.pub_time = pub_time
        self.update_time = update_time
        return self.save(allow_set_time=True)

    def __unicode__(self):
        return self.title

    meta = {
        'allow_inheritance': True,
        'indexes': ['slug'],
        'ordering': ['-pub_time']
    }

main/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from flask_mongoengine.wtf import model_form
from wtforms import StringField, PasswordField, BooleanField, TextAreaField, HiddenField
from wtforms import widgets, ValidationError
from wtforms.validators import Required, Length, Email, Regexp, EqualTo

import models

class PostForm(Form):
    title = StringField("Title", validators=[Required()])
    slug = StringField("Slug", validators=[Required()])
    raw = TextAreaField("Content")
    abstract = TextAreaField("Abstract")
    category = StringField("Category")
    tags_str = StringField("Tags")
    post_id = HiddenField("post_id")
    post_type = HiddenField("post_type")

    def validate_slug(self, field):
        posts = models.CPost.objects.filter(slug=field.data)
        if posts.count() > 0:
            if not self.post_id.data or str(posts[0].id) != self.post_id.data:
                raise ValidationError("slug already in use")

SuPostFrom = model_form(models.CPost, exclude=["pub_time", "update_time",
                                               "content_html", "category",
                                               "tags", "post_type"])

main/views.py
# -*- coding: utf-8 -*-

from VchanBlog.defines import *
from urlparse import urljoin
from flask import request, render_template, abort, current_app, make_response
from flask_login import current_user
from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q

import models
import datetime


def get_base_data():
    pages = models.CPost.objects.filter(post_type="page", is_draft=False)
    blog_meta = VchanBlogSettings["blog_meta"]
    data = {"blog_meta":blog_meta,
            "pages":pages,}
    return data

def list_posts():
    posts = models.CPost.objects.filter(post_type="post", is_draft=False).order_by("-pub_time")
    tags = posts.distinct('tags')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)
    keywords = request.args.get('keywords')

    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=int(cur_page), per_page=PER_PAGE)

    #group by aggregate
    category_cursor = models.CPost._get_collection().aggregate([
            { '$group' :
                { '_id' : {'category' : '$category' },
                  'name' : { '$first' : '$category' },
                  'count' : { '$sum' : 1 },
                }
            }
        ])

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    return render_template('main/index.html', **data)

def recent_feed():
    feed = AtomFeed('Recent Articles', feed_url=request.url, url=request.url_root)

    posts = models.CPost.objects.filter(post_type='post', is_draft=False)[:15]
    for post in posts:
        # return post.get_absolute_url()
        feed.add(post.title, unicode(post.content_html),
                 content_type='html',
                 author=post.author.username,
                 url=make_external(post.get_absolute_url()),
                 updated=post.update_time,
                 published=post.pub_time)
    return feed.get_response()

def make_external(url):
    return urljoin(request.url_root, url)

def archive():
    posts = models.CPost.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['posts'] = posts

    return render_template('main/archive.html', **data)

def post_detail(slug, post_type='post', fix=False):
    post = models.CPost.objects.get_or_404(slug=slug, post_type=post_type) if not fix \
        else models.CPost.objects.get_or_404(fix_slug=slug, post_type=post_type)

    if post.is_draft and current_user.isanonymous:
        abort(404)

    data = get_base_data()

    data_ext = {
        "post": post,
        "allow_donate": VchanBlogSettings["donation"]["allow_donate"],
        "donation_msg": VchanBlogSettings["donation"]["donation_msg"],
        "allow_comment": VchanBlogSettings["blog_comment"]["allow_comment"],
        "allow_share_article": VchanBlogSettings["allow_share_article"],
    }

    data.update(data_ext)

    if data["allow_comment"]:
        comment_type = VchanBlogSettings["blog_comment"]["comment_type"]
        comment_shortname = VchanBlogSettings["blog_comment"]["comment_opt"]["duoshuo"]
        comment_func = get_comment_func(comment_type)
        data["comment_html"] = comment_func(comment_shortname, slug, post.title, request.base_url) if comment_func else ""

    return render_template("main/post.html", **data)

def get_comment_func(comment_type):
    if comment_type == 'duoshuo':
        return duoshuo_comment
    else:
        return None

def duoshuo_comment(duoshuo_shortname, post_id, post_title, post_url):
    template_name = "main/misc/duoshuo.html"
    data = {
        "duoshuo_shortname": duoshuo_shortname,
        "post_id": post_id,
        "post_title": post_title,
        "post_url": post_url,
    }

    return render_template(template_name, **data)

def author_detail(username):
    author = models.CUser.objects.get_or_404(username=username)
    posts = models.CPost.objects.filter(post_type="post", is_draft=False, author=author).order_by("-pub_time")
    cur_page = request.args.get("page",1)
    posts = posts.paginate(page=int(cur_page), per_page=10)

    data = get_base_data()
    data["user"] = author
    data["posts"] = posts

    return render_template('main/author.html', **data)

def sitemap():
    pages = []
    ten_days_ago = (datetime.now() - datetime.timedelta(days=10)).date().isoformat()

    for rule in current_app.url_map.iter_rules():
        if "GET" in rule.methods and len(rule.arguments)==0:
            pages.append([rule.rule, ten_days_ago])

    posts = models.CPost.objects.filter(is_draft=False, post_type="post")
    for post in posts:
        pages.append((post.get_absolute_url(), post.update_time.date().isoformat()))

    blog_pages = models.CPost.objects.filter(is_draft=False, post_type="page")
    for page in blog_pages:
        pages.append((page.get_absolute_url(), page.update_time.date().isoformat()))

    sitemap_xml = render_template("main/sitemap.xml", pages=pages)
    response = make_response(sitemap_xml)
    response.headers["Content-Type"] = "application/xml"
    return response

templates/main/archive.html
{% extends 'base.html' %}

{% block title %}{{ blog_meta.name }}{% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ blog_meta.name }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ blog_meta.subtitle }} <a href="{{ url_for('main.recent_feed') }}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="row">
                {% for post in posts.items %}
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                      <!-- <img src="..." alt="..."> -->
                      <div class="caption">
                        <h3><a href="{{ url_for('main.post_detail', slug=post.slug) }}">{{ post.title }}</a></h3><hr>
                        <p><strong>Abstract: </strong>{{ post.abstract }}</p>
                        <p><strong>Author: </strong>{{ post.author }}</p>
                        <p><strong>Date: </strong>{{ post.pub_time.strftime('%Y/%m/%d') }}</p>
                        
                      </div>
                    </div>          
                </div>
                {% endfor %}
            </div>

            <div class="row">
                {% import '_pagination.html' as pagination %}
                {{ pagination.render_pagination(posts) }}
            </div>
        </div>

    </div>
</div>

<hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {

    location.href = "/";
    return false;
  });
</script>
{% endblock %}

templates/main/author.html
{% extends 'base.html' %}

{% block title %} Author | {{ user.display_name }} {% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-about-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ blog_meta.name }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ blog_meta.subtitle }} <a href="{{ url_for('main.recent_feed') }}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
{% block main %}
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="row">
                        <h3>About Author </h3>
                        <hr>
                        <dl class="dl-horizontal">
                            <dt>Display Name:</dt>
                            <dd>{{ user.display_name }}</dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Biography:</dt>
                            <dd>{{ user.biography }}</dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Social Network:</dt>
                            <dd>
                                {% if user.social_networks['github']['url'] %}
                                    <a href='{{ user.social_networks["github"]["url"] }}'><i class="fa fa-github fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['twitter']['url'] %}
                                    <a href='{{ user.social_networks["twitter"]["url"] }}'><i class="fa fa-twitter fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['weibo']['url'] %}
                                    <a href='{{ user.social_networks["weibo"]["url"] }}'><i class="fa fa-weibo fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['facebook']['url'] %}
                                    <a href='{{ user.social_networks["facebook"]["url"] }}'><i class="fa fa-facebook fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['linkedin']['url'] %}
                                    <a href='{{ user.social_networks["linkedin"]["url"] }}'><i class="fa fa-linkedin fa-lg"></i></a>
                                {% endif %}
                                {% if user.social_networks['weixin']['url'] %}
                                    <a id="btn_weixin" href='{{ user.social_networks["weixin"]["url"] }}'><i class="fa fa-weixin fa-lg"></i></a>
                                    <!-- weixin -->
                                    <div id="weixin" class="hidden">
                                        <br>
                                        <img src="{{ user.social_networks["weixin"]["url"] }}?imageView/2/w/150" title="weixin">
                                    </div> 
                                {% endif %}                
                            </dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Homepage:</dt>
                            <dd>
                                {% if user.homepage_url %}
                                <a href="{{ user.homepage_url }}"><i class="fa fa-home fa-lg"></i></a> {{ user.homepage_url }}
                                {% else %}
                                Not yet
                                {% endif %}
                            </dd>
                        </dl>
                    </div>
                    
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h3>Articles</h3><hr>
                    <ul>
                        {% for post in posts.items %}
                            <li><a href="{{ url_for('main.post_detail', slug=post.slug) }}">{{ post.title }}</a></li>
                        {% else %}
                            <p class="post-subtitle">No articles found here</p>
                        {% endfor %}
                    </ul>
                    <!-- Pager -->
                    <ul class="pager">
                        {% if posts.has_next %}
                        <li class="next">
                            <a href="?page={{ posts.next_num }}">Older Posts &rarr;</a>
                        </li>
                        {% endif %}
                        {% if posts.has_prev %}
                            <li class="next"><a href="?page={{ posts.prev_num }}">Previous Posts</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </article>
    <hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#btn_weixin').on('click', function(event){
        if($('#weixin').hasClass('hidden'))
            $('#weixin').removeClass('hidden');
        else
            $('#weixin').addClass('hidden');
        return false
    })
    
    
</script>
{% endblock %}

templates/main/index.html
{% extends 'base.html' %}

{% block title %}{{ blog_meta.name }}{% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('/static/img/home-header.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ blog_meta.name }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ blog_meta.subtitle }} <a href="{{ url_for('main.recent_feed') }}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-2 col-md-8 col-md-offset-1">
            {% for post in posts.items %}
            <div class="post-preview">
                <a href="{{ url_for('main.post_detail', slug=post.slug) }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                </a>
                <p class="post-subtitle">
                    {{ post.abstract }}
                </p>
                <p class="post-meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.pub_time.strftime('%Y/%m/%d %H:%M:%S') }}</p>
                <p class="post-meta">category: <a href="?category={{ post.category }}">{{ post.category }}</a></p>
                <p class="post-meta">Tags:
                            {% for tag in post.tags %} <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>  {% endfor %}
                </p>
            </div>
            {% if not loop.last %}
            <hr>
            {% endif %}
            {% else %}
                <p class="post-subtitle">
                    No articles found here
                </p>
            {% endfor %}
            <!-- Pager -->
            <ul class="pager">
                {% if posts.has_next %}
                <li class="next">
                    <a href="?page={{ posts.next_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Older Posts &rarr;</a>
                </li>
                {% endif %}
                {% if posts.has_prev %}
                    <li class="next"><a href="?page={{ posts.prev_num }}
                        {%- if cur_category %}&category={{ cur_category }}{% endif %}
                        {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Previous Posts</a></li>
                {% endif %}
            </ul>
        </div>
        

        <div class="col-lg-3 col-md-2">
            <h3>Search</h3><hr/>
            <form id="search-form">
              <div class="form-group">
                <div class="input-group">
                  <div class="input-group-addon"><i class="fa fa-search"></i></div>
                  <input type="text" class="form-control" id="search" name="keywords" placeholder="search" value="{% if keywords %}{{ keywords }}{% endif %}">
                </div>
              </div>
              <!-- <button type="submit" class="btn btn-default">Transfer cash</button> -->
            </form>
            <!-- <hr> -->
            <br>

            <h3>Tags</h3><hr/>
            {% for tag in tags %}
                <a href="?tag={{tag}}" class="post-tag">
                    {% if tag == cur_tag %}
                    <span class="label label-primary">
                        {{ tag }}
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                    </span>
                    
                    {% else %}
                    <span class="label label-default">
                        {{ tag }}
                    </span>
                    
                    {% endif %}
                    
                </a>
                &nbsp;
            {% endfor %}
            
            <h3>Category</h3><hr/>
            <div class="list-group">
                {% for category in category_cursor %}
                {% if category %}
                    {% if cur_category == category.name %}
                        <a href="?category={{ category.name }}" class="list-group-item category-list active">{{ category.name }} 
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                        <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
                    {% else %}
                        <a href="?category={{ category.name }}" class="list-group-item category-list ">{{ category.name }} 
                        <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
                    {% endif %}
                {% endif %}
                {% endfor %}
            </div>

                        
        </div>
    </div>
</div>

<hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {

    location.href = "/";
    return false;
  });
</script>
{% endblock %}

templates/main/post.html
{% extends 'base.html' %}
{% block title %} {{ post.title }} {% endblock %}

{% block custom_head %}
    <link href="{{ url_for('static', filename='css/share.min.css') }}" rel="stylesheet">
{% endblock %}

{% block header %}
<header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>{{ post.title }}</h1>
                        <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2> -->
                        <span class="meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.pub_time.strftime('%Y/%m/%d %H:%M:%S') }}</span>
                        <span class="meta">Category: <a href="{{ url_for('main.index') }}?category={{ post.category }}">{{ post.category }}</a></span>
                        <span class="meta">Tags:
                            {% for tag in post.tags %} <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>  {% endfor %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
{% block main %}
<div class="container">
    <article>
        <!-- <div class="container"> -->
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{post.content_html|safe}}
                </div>
            </div>
            {% if allow_share_article %}
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="share-component" data-sites="weibo,wechat,douban,twitter,qq,google,facebook,linkedin"></div>
                </div>

            </div>
            {% endif %}
            <br>
            {% if allow_donate %}
            <div class="row">
                <!-- donate -->
                <div class ="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p>{{ donation_msg }}</p>
                    <a id="btn_donate" class="btn_donate" href="#" title="Donate">
                    <i class="fa fa-usd"></i> | <i class="fa fa-jpy"></i>
                    </a>                  
                    <br>
                </div>
                <!-- donate --> 
                
            </div>
            
            {% endif %}
            
        <!-- </div> -->
    </article>
    <br>
    <hr>
    {% if allow_comment %}
        <article>
            <!-- <div class="container"> -->
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        {{ comment_html|safe }}
                    </div>
                </div>
            <!-- </div> -->
        </article>
    {% endif %}
</div>
{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/share.min.js') }}"></script>
<script type="text/javascript">
    $('#btn_donate').on('click', function(event){
        if($('#donate_guide').hasClass('hidden'))
            $('#donate_guide').removeClass('hidden');
        else
            $('#donate_guide').addClass('hidden');
        return false
    })
    
    
</script>
{% endblock %}