main/urls.py
# -*- coding: utf-8 -*-

from flask import Blueprint

import views
import admin_views
import errors

main = Blueprint("main", __name__)
# __name__ : main.urls


main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail)
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={"fix": True})
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type': "page"})
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)
main.errorhandler(404)(errors.page_not_found)



blog_admin = Blueprint("blog_admin", __name__)

blog_admin.add_url_rule("/", view_func=admin_views.AdminIndex.as_view("index"))
blog_admin.add_url_rule("/posts/", view_func=admin_views.PostsList.as_view("posts"))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('posts/<slug>', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view("su_posts"))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

main/views.py
# -*- coding: utf-8 -*-

from VchanBlog.defines import *
from urlparse import urljoin
from flask import request, render_template, abort, current_app, make_response
from flask_login import current_user
from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q

import models
import datetime


def get_base_data():
    pages = models.CPost.objects.filter(post_type="page", is_draft=False)
    blog_meta = VchanBlogSettings["blog_meta"]
    data = {"blog_meta":blog_meta,
            "pages":pages,}
    return data

def list_posts():
    posts = models.CPost.objects.filter(post_type="post", is_draft=False).order_by("-pub_time")
    tags = posts.distinct('tags')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)
    keywords = request.args.get('keywords')

    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=int(cur_page), per_page=PER_PAGE)

    #group by aggregate
    category_cursor = models.CPost._get_collection().aggregate([
            { '$group' :
                { '_id' : {'category' : '$category' },
                  'name' : { '$first' : '$category' },
                  'count' : { '$sum' : 1 },
                }
            }
        ])

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    return render_template('main/index.html', **data)

def recent_feed():
    feed = AtomFeed('Recent Articles', feed_url=request.url, url=request.url_root)

    posts = models.CPost.objects.filter(post_type='post', is_draft=False)[:15]
    for post in posts:
        # return post.get_absolute_url()
        feed.add(post.title, unicode(post.content_html),
                 content_type='html',
                 author=post.author.username,
                 url=make_external(post.get_absolute_url()),
                 updated=post.update_time,
                 published=post.pub_time)
    return feed.get_response()

def make_external(url):
    return urljoin(request.url_root, url)

def archive():
    posts = models.CPost.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['posts'] = posts

    return render_template('main/archive.html', **data)

def post_detail(slug, post_type='post', fix=False):
    post = models.CPost.objects.get_or_404(slug=slug, post_type=post_type) if not fix \
        else models.CPost.objects.get_or_404(fix_slug=slug, post_type=post_type)

    if post.is_draft and current_user.isanonymous:
        abort(404)

    data = get_base_data()

    data_ext = {
        "post": post,
        "allow_donate": VchanBlogSettings["donation"]["allow_donate"],
        "donation_msg": VchanBlogSettings["donation"]["donation_msg"],
        "allow_comment": VchanBlogSettings["blog_comment"]["allow_comment"],
        "allow_share_article": VchanBlogSettings["allow_share_article"],
    }

    data.update(data_ext)

    if data["allow_comment"]:
        comment_type = VchanBlogSettings["blog_comment"]["comment_type"]
        comment_shortname = VchanBlogSettings["blog_comment"]["comment_opt"]["duoshuo"]
        comment_func = get_comment_func(comment_type)
        data["comment_html"] = comment_func(comment_shortname, slug, post.title, request.base_url) if comment_func else ""

    return render_template("main/post.html", **data)

def get_comment_func(comment_type):
    if comment_type == 'duoshuo':
        return duoshuo_comment
    else:
        return None

def duoshuo_comment(duoshuo_shortname, post_id, post_title, post_url):
    template_name = "main/misc/duoshuo.html"
    data = {
        "duoshuo_shortname": duoshuo_shortname,
        "post_id": post_id,
        "post_title": post_title,
        "post_url": post_url,
    }

    return render_template(template_name, **data)

def author_detail(username):
    author = models.CUser.objects.get_or_404(username=username)
    posts = models.CPost.objects.filter(post_type="post", is_draft=False, author=author).order_by("-pub_time")
    cur_page = request.args.get("page",1)
    posts = posts.paginate(page=int(cur_page), per_page=10)

    data = get_base_data()
    data["user"] = author
    data["posts"] = posts

    return render_template('main/author.html', **data)

def sitemap():
    pages = []
    ten_days_ago = (datetime.now() - datetime.timedelta(days=10)).date().isoformat()

    for rule in current_app.url_map.iter_rules():
        if "GET" in rule.methods and len(rule.arguments)==0:
            pages.append([rule.rule, ten_days_ago])

    posts = models.CPost.objects.filter(is_draft=False, post_type="post")
    for post in posts:
        pages.append((post.get_absolute_url(), post.update_time.date().isoformat()))

    blog_pages = models.CPost.objects.filter(is_draft=False, post_type="page")
    for page in blog_pages:
        pages.append((page.get_absolute_url(), page.update_time.date().isoformat()))

    sitemap_xml = render_template("main/sitemap.xml", pages=pages)
    response = make_response(sitemap_xml)
    response.headers["Content-Type"] = "application/xml"
    return response

templates/blog_admin/401.html
{% extends 'admin_base.html' %}

{%block main %}
<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <h3>401 Error</h3>
        <p>Your requests is unauthorized</p>
    </div>
    
</div>
{% endblock %}

{% block js %}

{% endblock %}

templates/blog_admin/index.html
{% extends 'admin_base.html' %}

{%block main %}
<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <h3>Blog Meta Data</h3><hr>
        <dl class="dl-horizontal">
            <dt>Blog Name:</dt>
            <dd>{{ blog_meta.name }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Subtitle:</dt>
            <dd>{{ blog_meta.subtitle }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Description:</dt>
            <dd>{{ blog_meta.description }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Owner:</dt>
            <dd>{{ blog_meta.owner }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Keywords:</dt>
            <dd>{{ blog_meta.keywords }}</dd>
        </dl>
    </div>
    <div class="row">
        <h3>
            About User &nbsp;
            <small><a href="{{ url_for('accounts.settings') }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></small>
        </h3>
        <hr>
        <dl class="dl-horizontal">
            <dt>Username Name:</dt>
            <dd>{{ user.username }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Display Name:</dt>
            <dd>{{ user.display_name }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Biography:</dt>
            <dd>{{ user.biography }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Social Network:</dt>
            <dd>
                {% if user.social_networks['github']['url'] %}
                    <a href='{{ user.social_networks["github"]["url"] }}'><i class="fa fa-github fa-lg"></i></a>
                {% endif %}
                {% if user.social_networks['twitter']['url'] %}
                    <a href='{{ user.social_networks["twitter"]["url"] }}'><i class="fa fa-twitter fa-lg"></i></a>
                {% endif %}
                {% if user.social_networks['weibo']['url'] %}
                    <a href='{{ user.social_networks["weibo"]["url"] }}'><i class="fa fa-weibo fa-lg"></i></a>
                {% endif %}
                {% if user.social_networks['facebook']['url'] %}
                    <a href='{{ user.social_networks["facebook"]["url"] }}'><i class="fa fa-facebook fa-lg"></i></a>
                {% endif %}
                {% if user.social_networks['linkedin']['url'] %}
                    <a href='{{ user.social_networks["linkedin"]["url"] }}'><i class="fa fa-linkedin fa-lg"></i></a>
                {% endif %}
                {% if user.social_networks['weixin']['url'] %}
                    <a id="btn_weixin" href='{{ user.social_networks["weixin"]["url"] }}'><i class="fa fa-weixin fa-lg"></i></a>
                    <!-- weixin -->
                    <div id="weixin" class="hidden">
                        <br>
                        <img src="{{ user.social_networks["weixin"]["url"] }}?imageView/2/w/150" title="weixin">
                    </div> 
                {% endif %}                
            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Homepage:</dt>
            <dd>
                {% if user.homepage_url %}
                <a href="{{ user.homepage_url }}"><i class="fa fa-home fa-lg"></i></a> {{ user.homepage_url }}
                {% else %}
                Not yet
                {% endif %}
            </dd>
        </dl>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $('#btn_weixin').on('click', function(event){
        if($('#weixin').hasClass('hidden'))
            $('#weixin').removeClass('hidden');
        else
            $('#weixin').addClass('hidden');
        return false
    })
    
    
</script>
{% endblock %}

templates/blog_admin/post.html
{% extends "admin_base.html" %}

{% block title %}
    {% if edit_flag %}
        Edit {{ form.post_type.data|capitalize }}
    {% else %}
        New {{ form.post_type.data|capitalize }}
    {% endif %}
{% endblock %}

{% block css %}
    <link href="//cdn.bootcss.com/bootstrap-markdown/2.9.0/css/bootstrap-markdown.min.css" rel="stylesheet">
{% endblock %}

{% block main %}

<form method="POST" action="" id='new-post'>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                {% import "_form.html" as forms %}
                {{ form.csrf_token() }}
                {{ form.post_id() }}
                {{ form.post_type() }}
                {% if form.title.errors %}
                    <div class="clearfix has-error form-group">
                    {{ form.title.label }}
                    {{ form.title(class_="form-control") }}
                    <span class="help-block">{{ form.title.errors|join(' ') }}</span>
                    </div>
                {% else %}
                    <div class="form-group">
                    {{ form.title.label }}
                    {{ form.title(class_="form-control") }}
                    </div>
                {% endif %}

                {% if form.slug.errors %}
                    <div class="clearfix has-error form-group">
                    {{ form.slug.label }}
                    {{ form.slug(class_="form-control") }}
                    <!-- <span class="help-block">{{ url_for('main.post_detail', slug=display_slug) }}</span> -->
                    <span class="help-block">{{ form.slug.errors|join(' ') }}</span>
                    </div>
                {% else %}
                    <div class="form-group">
                    {{ form.slug.label }}
                    {{ form.slug(class_="form-control") }}
                    <!-- <span class="help-block">{{ url_for('main.post_detail', slug=display_slug) }}</span> -->
                    </div>
                {% endif %}

                <div class="form-group">
                    {{ form.raw.label }}

                    {{ form.raw(class_="form-control", rows=30, data_provide="markdown") }}
                </div>

                <div class="form-group">
                    {{ form.abstract.label }}
                    {{ form.abstract(class_="form-control", rows=5) }}
                </div>

            </div>
        
            <div class="row">
                <div class="col-md-5">
                    <h3>Tags</h3>
                    <hr>
                    <div class="input-group">
                          {{ form.tags_str(class_="form-control") }}
                          <div class="input-group-btn">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
                            <ul class="dropdown-menu dropdown-menu-right">
                                {% for tag in tags %}
                                    <li><a href="#" class="tag" data-tag="{{ tag }}">{{ tag }}</a></li>
                                {% endfor %}
                            </ul>
                          </div><!-- /btn-group -->
                    </div>
                </div>
                
                <div class="col-md-5">
                    <h3>Category</h3>
                        <hr>
                        <div class="input-group">
                          {{ form.category(class_="form-control") }}
                          <div class="input-group-btn">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></button>
                            <ul class="dropdown-menu dropdown-menu-right">
                                {% for category in categories %}
                                    <li><a href="#" class="category-name" data-category="{{ category }}">{{ category }}</a></li>
                                {% endfor %}
                            </ul>
                          </div><!-- /btn-group -->
                        </div>
                </div>
            </div>
            <br><br><br><br>
            <div class="row">
                <button type="submit" class="btn btn-primary" name="publish" value="publish">Publish</button>
                <button type="submit" class="btn btn-success" name="draft" value="draft">Save draft</button>
                <!-- <button type="submit" class="btn btn-default" name="preview" value="preview" id="btn-preview">Preview</button> -->
            </div>
        
        </div>
    </div>
            
    
</form>
{% endblock %}

{% block js %}
<script src="//cdn.bootcss.com/marked/0.3.5/marked.min.js"></script>
<script src="//cdn.bootcss.com/to-markdown/1.3.0/to-markdown.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap-markdown/2.9.0/js/bootstrap-markdown.min.js"></script>
<script type="text/javascript">
    // using jQuery

    // wideArea();
    
    $('.tag').on('click', function(event){
        var tag = $(this).data('tag');
        // alert(category);
        var elem = document.getElementById("tags_str");
        if(elem.value==''){
            elem.value = tag;
        }else{
            // elem.value += ', ';
            // elem.value += tag;
            elem.value = [elem.value, tag].join(', ')
        }

        // $(this).remove();
        return false
    });

    $('.category-name').on('click', function(event){
        var category = $(this).data('category');
        // alert(category);
        var elem = document.getElementById("category");
        elem.value = category;

        return false
    });

</script>
{% endblock %}

templates/blog_admin/posts.html
{% extends "admin_base.html" %}
{% block title %}{{ post_type|capitalize }}s{% endblock %}
{% block main %}
<div class="row">
    <!-- <div class="col-md-10"> -->
    <!-- <h1>New Post</h1> -->
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th style="width: 15%" >Title</th>
                <th>Abstract</th>
                <th>Author</th>
                <th style="width: 10%">Publish</th>
                <th style="width: 10%">Update</th>
                <th style="width: 5%">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts.items %}
            <tr id="post-{{ post.id }}">
                <td>{{ loop.index }}</td>
                <td>
                    {% if post_type=='page' %}
                    <a href="{{ url_for('main.page_detail', slug=post.slug) }}" target="_blank">{{ post.title }}</a>
                    {% else %}
                    <a href="{{ url_for('main.post_detail', slug=post.slug) }}" target="_blank">{{ post.title }}</a>
                    {% endif %}                    
                </td>
                <td>{{ post.abstract }}</td>
                <td>{{ post.author.username }}</td>
                <td>{{ post.pub_time.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                <td>{{ post.update_time.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                <td>
                    <a href="{{ url_for('blog_admin.edit_post', slug=post.slug) }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                    &nbsp
                    <a href="{{ url_for('blog_admin.edit_post', slug=post.slug) }}"  class="del-post"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% else %}
            <tr><td colspan="7" style="text-align: left">No {{ post_type }}s yet</td></tr>
            {% endfor %}      
        </tbody>
    </table>
    {% import '_pagination.html' as pagination %}
    {{ pagination.render_pagination(posts) }}
    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
$('.del-post').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');
    url = url + '?ajax=true';
    bootbox.confirm("Are you sure?", function(result) {
      if(result){
        // $.get(url, function(){
        //     location.reload();
        // });
        $.ajax({
            url: url,
            type: 'DELETE',
            success: function(result){
                location.reload();
            }

        })
        }
    });
    return false;
  });
</script>
{% endblock %}

templates/blog_admin/su_post.html
{% extends "admin_base.html" %}

{% block title %}
    Edit
{% endblock %}

{% block css %}
<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
{% endblock %}

{% block main %}

<!-- <form method="POST" action="" id='new-post'>
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            
            <br><br><br><br>
            <div class="row">
                <button type="submit" class="btn btn-primary" name="publish" value="publish">submit</button>
                
            </div>
        
        </div>
    </div>
            
    
</form> -->
<div class="col-md-6 col-md-offset-1">
    <h3>Edit</h3>
    <hr>
    {% import "_form.html" as forms %}
    <form method="POST" action="">
        {{ forms.render(form) }}

        <div class="form-group">
            <label for="post_type">Post Type</label>
            <!-- <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email"> -->
            <select class="form-control" id="post_type" name="post_type">
                {% for post_type in post_types %}
                <option value="{{ post_type }}" {% if post_type==post.post_type %}selected{% endif %} >{{ post_type }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label for="publish_time">Publish Time</label>
            <div class='input-group date' id='publish_time'>
                <input type='text' class="form-control" name="publish_time" value="{{ post.pub_time.strftime('%Y-%m-%d %H:%M:%S') }}" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>

        <div class="form-group">
            <label for="update_time">Update Time</label>
            <div class='input-group date' id='update_time'>
                <input type='text' class="form-control" name="update_time" value="{{ post.update_time.strftime('%Y-%m-%d %H:%M:%S') }}" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary" name="user" value="user">Submit</button>
    </form>
</div>

{% endblock %}

{% block js %}
<script src="//cdn.bootcss.com/moment.js/2.10.6/moment.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

<script type="text/javascript">
    // using jQuery
    
    $('.tag').on('click', function(event){
        var tag = $(this).data('tag');
        // alert(category);
        var elem = document.getElementById("tags_str");
        if(elem.value==''){
            elem.value = tag;
        }else{
            // elem.value += ', ';
            // elem.value += tag;
            elem.value = [elem.value, tag].join(', ')
        }

        // $(this).remove();
        return false
    });

    $('.category-name').on('click', function(event){
        var category = $(this).data('category');
        // alert(category);
        var elem = document.getElementById("category");
        elem.value = category;

        return false
    });

    $(function () {
        $('.date').datetimepicker({format:'YYYY-MM-DD HH:mm:ss'});
    }); 

</script>
{% endblock %}

templates/blog_admin/su_posts.html
{% extends "admin_base.html" %}
{% block title %}All Posts of all types{% endblock %}
{% block main %}
<div class="row">
    <!-- <div class="col-md-10"> -->
    <!-- <h1>New Post</h1> -->
    <a href="."><span class="label label-default">All</span></a>&nbsp;
    {% for post_type in post_types %}
        <a href="?type={{ post_type }}" class="post-tag">
            {% if post_type == cur_type %}
            <span class="label label-primary">
                {{ post_type }}
                <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
            </span>
            
            {% else %}
            <span class="label label-default">
                {{ post_type }} 
            </span>
            
            {% endif %}
            
        </a>
        &nbsp;
    {% endfor %}
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th style="width: 15%">Title</th>
                <th>Abstract</th>
                <th>Author</th>
                <th style="width: 10%">Publish Date</th>
                <th style="width: 10%">Update Date</th>
                <th style="width: 5%">PostType</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts.items %}
            <tr id="post-{{ post.id }}">
                <td>{{ loop.index }}</td>
                <td>
                    <a href="#" target="_blank">{{ post.title }}</a>              
                </td>
                <td>{{ post.abstract }}</td>
                <td>{{ post.author.username }}</td>
                <td>{{ post.pub_time.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                <td>{{ post.update_time.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                <td>{{ post.post_type }}</td>
                <td>
                    <a href="{{ url_for('blog_admin.su_post_edit', slug=post.slug) }}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                    &nbsp
                    <a href="{{ url_for('blog_admin.edit_post', slug=post.slug) }}"  class="del-post"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% else %}
            <tr><td colspan="8" style="text-align: left">No posts yet</td></tr>
            {% endfor %}      
        </tbody>
    </table>

    {% import '_pagination.html' as pagination %}
    {{ pagination.render_pagination(posts) }}

    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
$('.del-post').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');
    url = url + '?ajax=true';
    bootbox.confirm("Are you sure?", function(result) {
      if(result){
        // $.get(url, function(){
        //     location.reload();
        // });
        $.ajax({
            url: url,
            type: 'DELETE',
            success: function(result){
                location.reload();
            }

        })
        }
    });
    return false;
  });

$('.rm-filter').on('click', function (event) {

    location.href = "{{ url_for('blog_admin.su_posts') }}";
    return false;
  });
</script>

{% endblock %}