main/urls.py
# -*- coding: utf-8 -*-

from flask import Blueprint

import views
import admin_views
import errors

main = Blueprint("main", __name__)
# __name__ : main.urls


main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail)
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={"fix": True})
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail, defaults={'post_type': "page"})
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)
main.errorhandler(404)(errors.page_not_found)



blog_admin = Blueprint("blog_admin", __name__)

blog_admin.add_url_rule("/", view_func=admin_views.AdminIndex.as_view("index"))
blog_admin.add_url_rule("/posts/", view_func=admin_views.PostsList.as_view("posts"))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type': 'page'})
blog_admin.add_url_rule('posts/<slug>', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view("su_posts"))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

main/views.py
# -*- coding: utf-8 -*-

from VchanBlog.defines import *
from urlparse import urljoin
from flask import request, render_template, abort, current_app, make_response
from flask_login import current_user
from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q

import models
import datetime


def get_base_data():
    pages = models.CPost.objects.filter(post_type="page", is_draft=False)
    blog_meta = VchanBlogSettings["blog_meta"]
    data = {"blog_meta":blog_meta,
            "pages":pages,}
    return data

def list_posts():
    posts = models.CPost.objects.filter(post_type="post", is_draft=False).order_by("-pub_time")
    tags = posts.distinct('tags')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)
    keywords = request.args.get('keywords')

    if keywords:
        # posts = posts.filter(raw__contains=keywords )
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=int(cur_page), per_page=PER_PAGE)

    #group by aggregate
    category_cursor = models.CPost._get_collection().aggregate([
            { '$group' :
                { '_id' : {'category' : '$category' },
                  'name' : { '$first' : '$category' },
                  'count' : { '$sum' : 1 },
                }
            }
        ])

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    return render_template('main/index.html', **data)

def recent_feed():
    feed = AtomFeed('Recent Articles', feed_url=request.url, url=request.url_root)

    posts = models.CPost.objects.filter(post_type='post', is_draft=False)[:15]
    for post in posts:
        # return post.get_absolute_url()
        feed.add(post.title, unicode(post.content_html),
                 content_type='html',
                 author=post.author.username,
                 url=make_external(post.get_absolute_url()),
                 updated=post.update_time,
                 published=post.pub_time)
    return feed.get_response()

def make_external(url):
    return urljoin(request.url_root, url)

def archive():
    posts = models.CPost.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['posts'] = posts

    return render_template('main/archive.html', **data)

def post_detail(slug, post_type='post', fix=False):
    post = models.CPost.objects.get_or_404(slug=slug, post_type=post_type) if not fix \
        else models.CPost.objects.get_or_404(fix_slug=slug, post_type=post_type)

    if post.is_draft and current_user.isanonymous:
        abort(404)

    data = get_base_data()

    data_ext = {
        "post": post,
        "allow_donate": VchanBlogSettings["donation"]["allow_donate"],
        "donation_msg": VchanBlogSettings["donation"]["donation_msg"],
        "allow_comment": VchanBlogSettings["blog_comment"]["allow_comment"],
        "allow_share_article": VchanBlogSettings["allow_share_article"],
    }

    data.update(data_ext)

    if data["allow_comment"]:
        comment_type = VchanBlogSettings["blog_comment"]["comment_type"]
        comment_shortname = VchanBlogSettings["blog_comment"]["comment_opt"]["duoshuo"]
        comment_func = get_comment_func(comment_type)
        data["comment_html"] = comment_func(comment_shortname, slug, post.title, request.base_url) if comment_func else ""

    return render_template("main/post.html", **data)

def get_comment_func(comment_type):
    if comment_type == 'duoshuo':
        return duoshuo_comment
    else:
        return None

def duoshuo_comment(duoshuo_shortname, post_id, post_title, post_url):
    template_name = "main/misc/duoshuo.html"
    data = {
        "duoshuo_shortname": duoshuo_shortname,
        "post_id": post_id,
        "post_title": post_title,
        "post_url": post_url,
    }

    return render_template(template_name, **data)

def author_detail(username):
    author = models.CUser.objects.get_or_404(username=username)
    posts = models.CPost.objects.filter(post_type="post", is_draft=False, author=author).order_by("-pub_time")
    cur_page = request.args.get("page",1)
    posts = posts.paginate(page=int(cur_page), per_page=10)

    data = get_base_data()
    data["user"] = author
    data["posts"] = posts

    return render_template('main/author.html', **data)

def sitemap():
    pages = []
    ten_days_ago = (datetime.now() - datetime.timedelta(days=10)).date().isoformat()

    for rule in current_app.url_map.iter_rules():
        if "GET" in rule.methods and len(rule.arguments)==0:
            pages.append([rule.rule, ten_days_ago])

    posts = models.CPost.objects.filter(is_draft=False, post_type="post")
    for post in posts:
        pages.append((post.get_absolute_url(), post.update_time.date().isoformat()))

    blog_pages = models.CPost.objects.filter(is_draft=False, post_type="page")
    for page in blog_pages:
        pages.append((page.get_absolute_url(), page.update_time.date().isoformat()))

    sitemap_xml = render_template("main/sitemap.xml", pages=pages)
    response = make_response(sitemap_xml)
    response.headers["Content-Type"] = "application/xml"
    return response

templates/_form.html
{% macro render(form) -%}

{% for field in form %}
  {% if field.type in ['CSRFTokenField', 'HiddenField'] %}
    {{ field() }}
  {% elif field.type == "BooleanField" %}
  <div class="checkbox">
  <label>
    {{ field() }} {{ field.label }}
  </label>

  </div>
  {% else %}
    <div class="clearfix {% if field.errors %}has-error{% endif %} form-group">
      {{ field.label }}
        {{ field(class_="form-control") }}
        {% if field.errors or field.help_text %}
          <span class="help-block">
          {% if field.errors %}
            {{ field.errors|join(' ') }}
          {% else %}
            {{ field.help_text }}
          {% endif %}
          </span>
        {% endif %}
    </div>
  {% endif %}
{% endfor %}

{% endmacro %}

templates/_msg.html
{% macro render_msg() %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash_msg">
    {% for category, message in messages %}
      {% if category == 'message' %}
        {% set category='info' %}
      {% endif %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert" style="margin-bottom: 0px">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

{% endmacro %}

templates/_pagination.html
{% macro render_pagination(pagination) %}
  <nav>
    <ul class="pagination">
      {% if not pagination.has_prev %}
        <li class="disabled">
            <span aria-hidden="true">&laquo;</span>
        </li>
      {% else %}
        <li>
        <a href="?page={{ pagination.prev_num }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
      {% endif %}
    
      {%- for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="?page={{ page }}"><strong>{{ page }}</strong></a></li>
          {% endif %}
        {% else %}
          <span class=ellipsis>…</span>
        {% endif %}
      {%- endfor %}

      {% if not pagination.has_next %}
        <li class="disabled">
          <span aria-hidden="true">&raquo;</span>
        </li>
      {% else %}
        <li>
          <a href="?page={{ pagination.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}      
    </ul>
  </nav>
{% endmacro %}

templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}VChan Blog Admin{% endblock %}</title>
    
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">
    
    <!-- Bootstrap Core CSS -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/vchanblog.css') }}" rel="stylesheet">

    
    <!-- Custom CSS -->
    
    {% block css %}{% endblock %}
    <!-- Custom Fonts -->
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
{% import "_msg.html" as messages %}
{{ messages.render_msg() }}
    <!-- Navigation -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">VChan Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="_active"><a href="{{ url_for('blog_admin.index') }}">Home <span class="sr-only">(current)</span></a></li>
            
            {% if g.identity.allow_write %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Posts <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.posts') }}">All Posts</a></li>
                <li><a href="{{ url_for('blog_admin.new_post') }}">New Post</a></li>
                <li><a href="{{ url_for('blog_admin.posts') }}?draft=true">Drafts</a></li>

                <li class="divider"></li>
                <li><a href="#">Tags</a></li>
                
                <li class="divider"></li>
                <li><a href="#">Category</a></li>
              </ul>
            </li>
            {% endif %}

            {% if g.identity.allow_edit %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pages <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.pages') }}">All Pages</a></li>
                <li><a href="{{ url_for('blog_admin.new_page') }}">New Page</a></li>
                <li><a href="{{ url_for('blog_admin.pages') }}?draft=true">Drafts</a></li>
              </ul>
            </li>
            {% endif %}

            {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('accounts.users') }}">All Users</a></li>
                <li><a href="{{ url_for('accounts.add_user') }}">New User</a></li>
                <!-- <li class="divider"></li>
                <li><a href="#">User Groups</a></li> -->
                <!-- <li class="divider"></li>
                <li><a href="#">Category</a></li> -->
              </ul>
            </li>
            {% endif %}

            {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Super Admin <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.su_posts') }}">Posts & Pages</a></li>
                <li><a href="{{ url_for('accounts.su_users') }}">Users</a></li>
              </ul>
            </li>
            {% endif %}

          </ul>
          
            

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('accounts.settings') }}">Settings</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('accounts.logout') }}">Logout</a></li>
                <!-- <li class="divider"></li>
                <li><a href="#">Category</a></li> -->
              </ul>
            </li>
          {% else %}
            <li><a href="{{ url_for('accounts.login') }}">Login</a></li>
            <li><a href="{{ url_for('accounts.register') }}">Register</a></li>
          {% endif %}
          </ul>
        </div>
      </div><!-- /.container-fluid -->
    </nav>


    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <div class="container">
        <!-- Main Content -->
        
        {%block main %}{% endblock %}
    </div>
    <hr>
    
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/flyhigher139/VchanBlog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted text-center">Copyright &copy; VChan Blog 2016</p>
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/bootbox.js/4.4.0/bootbox.min.js"></script>
    
    <!-- Custom Theme JavaScript -->
    {% block js %}
    {% endblock %}
    
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    {% if post %}
    <meta name="title" content="{{ blog_meta.name }} | {{ post.title }}">
    <meta name="description" content="{{ post.abstract }}">
    <meta name="author" content="{{ post.author.username }}">
    <meta name="keywords" content="{{ post.tags|join(',') }}">
    {% else %}
    <meta name="title" content="{{ blog_meta.name }}">
    <meta name="description" content="{{ blog_meta.description }}">
    <meta name="author" content="{{ blog_meta.owner }}">
    <meta name="keywords" content="{{ blog_meta.keywords }}">
    {% endif %}

    <meta name="google-site-verification" content="{{ blog_meta.google_site_verification }}">
    <meta name="baidu-site-verification" content="{{ blog_meta.baidu_site_verification }}">

    <title>{% block title %}VChan Blog{% endblock %}</title>

    <!-- Bootstrap Core CSS -->

    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">

    <!-- <link href="http://cdn.staticfile.org/twitter-bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"> -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{ url_for('static', filename='css/clean-blog.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/vchanblog.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="http://cdn.staticfile.org/highlight.js/8.3/styles/default.min.css">

    <link href="{{ url_for('main.recent_feed') }}"
      rel="alternate"
      title="Recent Changes" 
      type="application/atom+xml">

    {% block custom_head %}{% endblock %}

    <!-- Custom Fonts -->
    <!-- <link href="http://libs.useso.com/js/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">VChan Blog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('main.recent_feed') }}" target="_blank">RSS</i></a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.archive') }}">Archive</i></a>
                    </li>

                   
                    {% for page in pages %}
                    <li>
                        <a href="{{ url_for('main.page_detail', slug=page.slug) }}">{{ page.slug }}</a>
                    </li>
                    {% endfor %}

                    <li>
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('blog_admin.index') }}">{{ current_user.username }}</i></a>
                        {% endif %}
                    </li>
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <!-- Main Content -->
    {%block main %}{% endblock %}
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="{{ url_for('main.recent_feed') }}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/flyhigher139/VchanBlog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; VChan Blog 2016</p>
                    <!--<p class="copyright text-muted"><a href="http://www.qiniu.com" target="_blank" ><img src="http://assets.qiniu.com/qiniu-transparent.png"></a></p>-->
                </div>
            </div>
        </div>
    </footer>
    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="//cdn.bootcss.com/highlight.js/8.7/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    {% block js %}
    {% endblock %}
</body>
</html>